version: '3'

services:
  backend:
    build:
      context: ./django_backend
    command: bash -c "./start_app.sh"
    container_name: HabitTracker_backend
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=HabitTracker
      - POSTGRES_USER=devusr
      - POSTGRES_PASSWORD=devusr1
    ports:
      - "5432:5432"

volumes:
  pgdata: