version: '3'

services:
  web:
    build:
      context: ./django_backend
    command: python3 manage.py runserver 0.0.0.0:8085
    container_name: web_server
    volumes:
      - ./django_backend:/HabitTracker
    ports:
      - "8085:8085"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=HabitTracker
      - POSTGRES_USER=devusr
      - POSTGRES_PASSWORD=devusr1
    ports:
      - "5432:5432"

volumes:
  pgdata:
  
