# Generated by Django 3.2.20 on 2024-03-08 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_expiringtoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 22, 8, 7, 759221, tzinfo=utc)),
        ),
    ]
