# Generated by Django 3.2.20 on 2024-03-09 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_expiringtoken_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiringtoken',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 19, 15, 19, 649939, tzinfo=utc)),
        ),
    ]
