POST http://127.0.0.1:8085/signup/
Content-Type: application/json

{
  "username": "adam12",
  "password": "Pass1234!",
  "email": "adam12@mail.com"
}

###

POST http://127.0.0.1:8085/login/
Content-Type: application/json

{
  "username": "adam12",
  "password": "Pass1234!"
}

###

GET http://127.0.0.1:8085/test_token/
Content-Type: application/json
Authorization: Token 134544c66592c7be325ae9b921ef2fe5a7e5fb6d

###
POST http://127.0.0.1:8085/logout/
Content-Type: application/json
Authorization: Token 134544c66592c7be325ae9b921ef2fe5a7e5fb6d

